#dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
#  - hhvm

before_script:
  #- cp .env.travis .env
  - cp .env.example .env
  #- mysql -e 'create database phpvms_test;'
  - composer self-update
  - make build

script:
  - make tests
