language: php
php:
- '7.0'
- '7.1'
- '7.2'
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS phpvms;'
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
script:
- php artisan database:create --reset
- php artisan migrate:refresh --seed
- cp tests/phpunit.travis.xml phpunit.xml
- vendor/bin/phpunit --debug --verbose
after_success:
- |
  if test "$TRAVIS_TAG"
  then
    echo "Branch name is $TRAVIS_TAG"
  else
    echo "no branch name detected"
  fi
env:
  matrix:
  - secure: TYqjGkzuhnQq+15ATA12t5yIOEND1l6mlOs7XwZrAqGnwBK2nmj9n28+Ujh6V1F/TZBUhBkm7prxhQmtyzX8xNAh4J2WUrnNNSmYxGQCRgQWk5yorDp3mZtk5o3qD9qvP+T5aeXh7k1+/w8N96warln8pGEb/y8oUDVzs6yPOX7cKEHn4EUX7qDVh43tUIl8e6BslHQB+r/0gn84HeKi8vIOtDg0Sozw07kRziRgTuz9hTIU6QVd+Z+oSlB4+m+y5TNVc5sPnpajpJtuUg+athGUlmsBfbstqrmZRcR6K/RQbYW8VAYwhEJSwYw3i4ZLpZXt4NPh5UioKDohULoTNdQLh7Im+TzwP0GEI1UjX8mqJRRlGenMz9cITH+DHL9tktfP66IsRB+Cv5BavYtpAqfJkXlOo5fuAy82Rj5+EwkpYom4JTUVW2bcDjwV8PBnjoJFBYzBT6PBvmzjAnWqM4UDe66ZfIXIW+7qsY1v83KI0wj37pK/YzYJNN9IC2DXBp9OUJeecQ6ofE+kM7GsO9xOe/9n1JuJZoFXSLLvUbeNBu1hALNeeh9yErfQT1cGv/baPBlV9Nvfhok3v4jOD6CjntTfblLB+C6Upm5Yf6J9fLxM9po5b0PtDvLT+KRL/I2DBwZpbeerT4Ht95A4cgYHstU9sBynfGVhuCjZPBg=
  - secure: QHd8x89IkesLBZQtxWAGzIvTM3Z7gIgKfYkAfNE7+DNACwc+fT0O06j5lYer92Gg2ALXjwTNaUBj3OI2aXRUsQ/SWSoYpxmPgCtfE3VkPAWEuQv3jENptLQtlHCWmZi0koqPLUQlpxx2UXN9kEWLijL3m8kZUsGXrS9MxpJxPghk3SLalVLlFXfDF1S3b7Fi6FmiDz946f7Ss375g1SCQ6RlMWswwRrLYRT8fLbbg/aweSK204iiZq56uQ1lln+2QtlcqCgMHD54VtIK5ja8vDGGaBiMvrn3bxGofABSQo/uUNLTU171XWtlzJ+mCxHnMXDCnswaRqFu8eCERFafpba0Lgl91YSN3MmnuEyNOFazJN6AfPQ4qbBTyaCy8HHo1HRoaUtZjZ6eknCWsgwY6ZlUie1QhmjIxuZ60HN8aO+H3J95T9NQSu8nXjWWqerggrNIFTIeSKJtgjTlUDkaLEMOqCzmJ7MRILZOEwA9R+rGkTFb2gEk7sdUlQfMUb0cP6G9XjgD6KUChmboPclJ0B+igc8zQwPr1KiQzQXhm82QyffDrCkzBzQ3Ymj+z9oAx5yx7eiz60zmiGyQaftxNQnHjwpQncrTM/vHNX+iFw4aqB83q6eZtJz1w6Be3vrqYGv7/42gCCrkhBs0pYSfCVg6YOIfzi4irVkNU6KYwZU=
