language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

#env:
#  - DB=mysql
#  - DB=mariadb

services:
  - mysql
#  - mariadb
  - redis-server

addons:
  ssh_known_hosts: phpvms.net

#before_install:
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS phpvms;'

before_script:
  - cp .travis/env.travis.php env.php
  - composer install --no-interaction --verbose

script:
  - php artisan database:create --reset
  - php artisan migrate:refresh --seed
  - cp .travis/phpunit.travis.xml phpunit.xml
  - vendor/bin/phpunit --debug --verbose

after_failure:
  - cat storage/logs/*.log

jobs:
  include:
    - stage: deploy
      script: skip
      before_deploy:
        - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
        #- openssl aes-256-cbc -K $encrypted_6ae8173eef05_key -iv $encrypted_6ae8173eef05_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
        #- eval "$(ssh-agent -s)"
        #- chmod 600 /tmp/deploy_rsa
        #- ssh-add /tmp/deploy_rsa
      deploy:
        provider: script
        skip_cleanup: true
        script: ./.travis/deploy_script.sh
        on:
            branch: master
            #condition: $DB = mysql
            php: '7.0'
