#dist: trusty
language: php
php:
  - '7.0'
  - '7.1'
#  - hhvm

services:
  - mysql

before_install:
   - mysql -e 'CREATE DATABASE IF NOT EXISTS phpvms;'

before_script:
  - cp .env.travis .env
  - composer self-update
  - make build

script:
  - make tests
