---
version: '3'

services:
  app:
    build:
      context: ./docker/php
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - nginx
      - mysql
      - redis

  nginx:
    image: nginx:1.15.12-alpine
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  mysql:
    image: mysql:5.7.26
    environment:
      MYSQL_DATABASE: phpvms
      MYSQL_USER: phpvms
      MYSQL_PASSWORD: phpvms
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:5.0.4-alpine

  # Use this to tail the logs so it's just all in a single window
  logs:
      image: busybox
      command: tail -f -F -n 0 /var/www/storage/logs/laravel.log
      restart: always
      volumes:
        - ./storage:/var/www/storage
      depends_on:
        - app
