---
swagger: "2.0"
info:
  version: "7.0"
  title: phpVMS API
  description: All of the responses are contained in the "data" variable
basePath: /api/v1
schemes:
  - https
paths:
  "/flights/search":
    get:
      summary: Retrieve all the applications and flags
      operationId: getFlightSearch
      parameters:
        - name: flight_id
          in: query
          type: string
          required: false
          description: ID of the flight
        - name: airline_id
          in: query
          type: string
          required: false
          description: ID of the airline
        - name: flight_number
          in: query
          type: string
          required: false
          description: Flight number to use
        - name: route_code
          in: query
          type: string
          required: false
          description: The route code
        - name: dep_icao
          in: query
          type: string
          required: false
          description: The departure ICAO
        - name: arr_icao
          in: query
          type: string
          required: false
          description: The arrival ICAO
        - name: dgt
          in: query
          type: integer
          required: false
          description: Flights with a distance greater than
        - name: dgt
          in: query
          type: integer
          required: false
          description: Flights with a distance greater than
      produces:
        - application/json
      responses:
        200:
          description: Returns flights from a search
          schema:
            $ref: '#/definitions/AppsWrapper'
      tags:
        - flights
